/**
 * Offline Spanish → English translator for immigration evidence.
 * Zero API calls, zero cost. Works entirely in the browser.
 * 
 * Strategy: apply longest-match-first phrase replacements,
 * then word-level fallback for remaining Spanish words.
 */

// Sorted longest-first so multi-word phrases match before their sub-words
const PHRASES: [RegExp, string][] = [
  // ── Multi-word phrases (must come first) ──
  [/\baquí estábamos\b/gi, 'here we were'],
  [/\baquí estabamos\b/gi, 'here we were'],
  [/\bestábamos\b/gi, 'we were'],
  [/\bestabamos\b/gi, 'we were'],
  [/\bmi mamá y yo\b/gi, 'my mother and I'],
  [/\bmi mama y yo\b/gi, 'my mother and I'],
  [/\bmi papá y yo\b/gi, 'my father and I'],
  [/\bmi papa y yo\b/gi, 'my father and I'],
  [/\bmi esposa y yo\b/gi, 'my wife and I'],
  [/\bmi esposo y yo\b/gi, 'my husband and I'],
  [/\bmi pareja y yo\b/gi, 'my partner and I'],
  [/\bmi familia y yo\b/gi, 'my family and I'],
  [/\bnuestra hija\b/gi, 'our daughter'],
  [/\bnuestro hijo\b/gi, 'our son'],
  [/\bnuestros hijos\b/gi, 'our children'],
  [/\bnuestra familia\b/gi, 'our family'],
  [/\bnuestra casa\b/gi, 'our home'],
  [/\bnuestro hogar\b/gi, 'our home'],
  [/\bla casa de mi\b/gi, 'at the home of my'],
  [/\ben casa de mi\b/gi, 'at the home of my'],
  [/\ben casa de\b/gi, 'at the home of'],
  [/\ben casa\b/gi, 'at home'],
  [/\bdía de acción de gracias\b/gi, 'Thanksgiving'],
  [/\baño nuevo\b/gi, "New Year's"],
  [/\breunión familiar\b/gi, 'family gathering'],
  [/\breunion familiar\b/gi, 'family gathering'],
  [/\bfin de semana\b/gi, 'weekend'],
  [/\bestado de cuenta\b/gi, 'bank statement'],
  [/\bcuenta bancaria\b/gi, 'bank account'],
  [/\breserva de vuelo\b/gi, 'flight reservation'],
  [/\bboleto de avión\b/gi, 'plane ticket'],
  [/\bboleto de avion\b/gi, 'plane ticket'],
  [/\bcoordinación de gastos\b/gi, 'coordination of expenses'],
  [/\bcoordinacion de gastos\b/gi, 'coordination of expenses'],
  [/\bgastos del hogar\b/gi, 'household expenses'],
  [/\bgastos compartidos\b/gi, 'shared expenses'],
  [/\bvida en común\b/gi, 'shared life'],
  [/\bvida en comun\b/gi, 'shared life'],
  [/\bpeticionario y beneficiario\b/gi, 'petitioner and beneficiary'],
  [/\bpeticionaria y beneficiaria\b/gi, 'petitioner and beneficiary'],
  [/\bel peticionario\b/gi, 'the petitioner'],
  [/\bla peticionaria\b/gi, 'the petitioner'],
  [/\bel beneficiario\b/gi, 'the beneficiary'],
  [/\bla beneficiaria\b/gi, 'the beneficiary'],
  [/\by su esposa\b/gi, 'and his wife'],
  [/\by su esposo\b/gi, 'and her husband'],
  [/\by su pareja\b/gi, 'and their partner'],
  [/\blos dos\b/gi, 'both of them'],
  [/\bla pareja\b/gi, 'the couple'],
  [/\bciudad de\b/gi, 'city of'],
  [/\bestado de\b/gi, 'state of'],
  [/\bviaje a\b/gi, 'trip to'],
  [/\bvisita a\b/gi, 'visit to'],
  [/\bde la\b/gi, 'of the'],
  [/\bde los\b/gi, 'of the'],
  [/\bde las\b/gi, 'of the'],
  [/\bdel\b/gi, 'of the'],
  [/\ben el\b/gi, 'at the'],
  [/\ben la\b/gi, 'at the'],
  [/\bcon el\b/gi, 'with the'],
  [/\bcon la\b/gi, 'with the'],
  [/\bcon su\b/gi, 'with their'],
  [/\bcon mi\b/gi, 'with my'],
  [/\bcon mis\b/gi, 'with my'],
  [/\bpara el\b/gi, 'for the'],
  [/\bpara la\b/gi, 'for the'],
  [/\bpor el\b/gi, 'for the'],
  [/\bpor la\b/gi, 'for the'],

  // ── Single words ──
  [/\bcelebrando\b/gi, 'celebrating'],
  [/\bcelebración\b/gi, 'celebration'],
  [/\bcelebracion\b/gi, 'celebration'],
  [/\bcumpleaños\b/gi, 'birthday'],
  [/\bcumpleanos\b/gi, 'birthday'],
  [/\bboda\b/gi, 'wedding'],
  [/\baniversario\b/gi, 'anniversary'],
  [/\bvacaciones\b/gi, 'vacation'],
  [/\bgraduación\b/gi, 'graduation'],
  [/\bgraduacion\b/gi, 'graduation'],
  [/\bnavidad\b/gi, 'Christmas'],
  [/\bfamilia\b/gi, 'family'],
  [/\bcena\b/gi, 'dinner'],
  [/\balmuerzo\b/gi, 'lunch'],
  [/\bdesayuno\b/gi, 'breakfast'],
  [/\brestaurante\b/gi, 'restaurant'],
  [/\bconcierto\b/gi, 'concert'],
  [/\bevento\b/gi, 'event'],
  [/\bparque\b/gi, 'park'],
  [/\bplaya\b/gi, 'beach'],
  [/\bmontaña\b/gi, 'mountain'],
  [/\bmontana\b/gi, 'mountain'],
  [/\bhospital\b/gi, 'hospital'],
  [/\bmédico\b/gi, 'doctor'],
  [/\bmedico\b/gi, 'doctor'],
  [/\baeropuerto\b/gi, 'airport'],
  [/\bhotel\b/gi, 'hotel'],
  [/\biglesia\b/gi, 'church'],
  [/\bescuela\b/gi, 'school'],
  [/\btienda\b/gi, 'store'],
  [/\bmercado\b/gi, 'market'],
  [/\bjuntos\b/gi, 'together'],
  [/\bjuntas\b/gi, 'together'],
  [/\bvisita\b/gi, 'visit'],
  [/\bviaje\b/gi, 'trip'],
  [/\bmudanza\b/gi, 'relocation'],
  [/\bplanificación\b/gi, 'planning'],
  [/\bplanificacion\b/gi, 'planning'],
  [/\bapoyo\b/gi, 'support'],
  [/\bcomunicación\b/gi, 'communication'],
  [/\bcomunicacion\b/gi, 'communication'],
  [/\brecibo\b/gi, 'receipt'],
  [/\bcomprobante\b/gi, 'proof'],
  [/\bfactura\b/gi, 'invoice'],
  [/\bcontrato\b/gi, 'contract'],
  [/\barrendamiento\b/gi, 'lease'],
  [/\btransferencia\b/gi, 'transfer'],
  [/\bpago\b/gi, 'payment'],
  [/\bseguro\b/gi, 'insurance'],
  [/\bpóliza\b/gi, 'policy'],
  [/\bpoliza\b/gi, 'policy'],
  [/\bpasaporte\b/gi, 'passport'],
  [/\bvisa\b/gi, 'visa'],
  [/\bacta\b/gi, 'certificate'],
  [/\bcertificado\b/gi, 'certificate'],
  [/\bboleto\b/gi, 'ticket'],
  [/\bticket\b/gi, 'ticket'],
  [/\bamigos\b/gi, 'friends'],
  [/\bcompañeros\b/gi, 'colleagues'],
  [/\bambos\b/gi, 'both'],
  [/\bpeticionario\b/gi, 'petitioner'],
  [/\bpeticionaria\b/gi, 'petitioner'],
  [/\bbeneficiario\b/gi, 'beneficiary'],
  [/\bbeneficiaria\b/gi, 'beneficiary'],
  [/\bmunicipio\b/gi, 'municipality'],
  [/\bhermana\b/gi, 'sister'],
  [/\bhermano\b/gi, 'brother'],
  [/\bmamá\b/gi, 'mother'],
  [/\bmama\b/gi, 'mother'],
  [/\bpapá\b/gi, 'father'],
  [/\bpapa\b/gi, 'father'],
  [/\babuela\b/gi, 'grandmother'],
  [/\babuelo\b/gi, 'grandfather'],
  [/\babuelos\b/gi, 'grandparents'],
  [/\btía\b/gi, 'aunt'],
  [/\btia\b/gi, 'aunt'],
  [/\btío\b/gi, 'uncle'],
  [/\btio\b/gi, 'uncle'],
  [/\bprimo\b/gi, 'cousin'],
  [/\bprima\b/gi, 'cousin'],
  [/\bsobrino\b/gi, 'nephew'],
  [/\bsobrina\b/gi, 'niece'],
  [/\bsuegra\b/gi, 'mother-in-law'],
  [/\bsuegro\b/gi, 'father-in-law'],
  [/\bcuñada\b/gi, 'sister-in-law'],
  [/\bcunada\b/gi, 'sister-in-law'],
  [/\bcuñado\b/gi, 'brother-in-law'],
  [/\bcunado\b/gi, 'brother-in-law'],
  [/\besposa\b/gi, 'wife'],
  [/\besposo\b/gi, 'husband'],
  [/\bhija\b/gi, 'daughter'],
  [/\bhijo\b/gi, 'son'],
  [/\bhijos\b/gi, 'children'],
  [/\bbebé\b/gi, 'baby'],
  [/\bbebe\b/gi, 'baby'],
  [/\bnovia\b/gi, 'girlfriend'],
  [/\bnovio\b/gi, 'boyfriend'],
  [/\bpareja\b/gi, 'partner'],
  [/\bfoto\b/gi, 'photo'],
  [/\bfotos\b/gi, 'photos'],
  [/\bcasa\b/gi, 'home'],
  [/\bhogar\b/gi, 'home'],
  [/\btrabajo\b/gi, 'work'],
  [/\boficina\b/gi, 'office'],
  [/\bcocina\b/gi, 'kitchen'],
  [/\bjardín\b/gi, 'garden'],
  [/\bjardin\b/gi, 'garden'],
  [/\bpiscina\b/gi, 'pool'],
  [/\bfiesta\b/gi, 'party'],
  [/\breunión\b/gi, 'gathering'],
  [/\breunion\b/gi, 'gathering'],
  [/\bcomida\b/gi, 'meal'],
  [/\bpaseo\b/gi, 'outing'],
  [/\bcaminata\b/gi, 'walk'],
  [/\bdía\b/gi, 'day'],
  [/\bdia\b/gi, 'day'],
  [/\bnoche\b/gi, 'night'],
  [/\btarde\b/gi, 'afternoon'],
  [/\bmañana\b/gi, 'morning'],
  [/\bmanana\b/gi, 'morning'],
  [/\bfeliz\b/gi, 'happy'],
  [/\bespecial\b/gi, 'special'],
  [/\bprimera\b/gi, 'first'],
  [/\bprimer\b/gi, 'first'],

  // ── Common verbs ──
  [/\bfuimos\b/gi, 'we went'],
  [/\bfueron\b/gi, 'they went'],
  [/\bestuvimos\b/gi, 'we were'],
  [/\bvisitamos\b/gi, 'we visited'],
  [/\bcompartimos\b/gi, 'we shared'],
  [/\bcocinamos\b/gi, 'we cooked'],
  [/\bpaseamos\b/gi, 'we walked'],
  [/\bviajamos\b/gi, 'we traveled'],
  [/\bsalimos\b/gi, 'we went out'],
  [/\bcomimos\b/gi, 'we ate'],
  [/\bcenamos\b/gi, 'we had dinner'],
  [/\bdesayunamos\b/gi, 'we had breakfast'],
  [/\balmorzamos\b/gi, 'we had lunch'],
  [/\bfestejamos\b/gi, 'we celebrated'],

  // ── Common connectors ──
  [/\bcon\b/gi, 'with'],
  [/\ben\b/gi, 'in'],
  [/\bpara\b/gi, 'for'],
  [/\bpor\b/gi, 'for'],
  [/\bde\b/gi, 'of'],
  [/\by\b/gi, 'and'],
  [/\bo\b/gi, 'or'],
  [/\bmi\b/gi, 'my'],
  [/\bmis\b/gi, 'my'],
  [/\bsu\b/gi, 'their'],
  [/\bsus\b/gi, 'their'],
  [/\bel\b/gi, 'the'],
  [/\bla\b/gi, 'the'],
  [/\blos\b/gi, 'the'],
  [/\blas\b/gi, 'the'],
  [/\bun\b/gi, 'a'],
  [/\buna\b/gi, 'a'],
];

/**
 * Translates common Spanish phrases to English locally.
 * No API calls, no cost. Works offline.
 */
export function translateToEnglish(text: string): string {
  if (!text || !text.trim()) return text;

  // Quick check: if text looks already English, return as-is
  const englishWords = /\b(the|and|with|trip|photo|birthday|wedding|our|their|both|visit|family|dinner|lunch|beach|airport|hotel|party|christmas|celebration|celebrating|together|we were)\b/i;
  if (englishWords.test(text)) return text;

  let result = text;
  for (const [pattern, replacement] of PHRASES) {
    result = result.replace(pattern, replacement);
  }

  // Capitalize first letter
  return result.charAt(0).toUpperCase() + result.slice(1);
}

/**
 * Returns DEMONSTRATES value always in English (for PDF).
 */
const DEMONSTRATES_EN_MAP: Record<string, string> = {
  'Comunicación constante': 'Ongoing communication',
  'Coordinación de vida en común': 'Coordination of shared life',
  'Apoyo emocional': 'Emotional support',
  'Apoyo financiero': 'Financial support',
  'Planificación de viaje / mudanza': 'Travel / relocation planning',
  'Relación romántica': 'Romantic relationship',
  'Otro': 'Other',
};

export function demonstratesToEnglish(value: string): string {
  return DEMONSTRATES_EN_MAP[value] || value;
}
