-- ═══════════════════════════════════════════════════════════════════
-- NO-OP MIGRATION — superseded by 20260514192216_events_table.sql
-- ═══════════════════════════════════════════════════════════════════
--
-- Origen: Lovable creó esta migration como copia funcional idéntica de
--   20260514192216_events_table.sql al aplicar el deploy de Ola 1.
--   Ambas tienen el mismo CREATE TABLE IF NOT EXISTS, mismas policies,
--   misma función events_retention_cleanup.
--
-- Problema detectado en audit ronda 2 (2026-05-14):
--   CREATE POLICY NO soporta IF NOT EXISTS en Postgres < 15.
--   Si Supabase corre las 2 migrations en orden, la segunda tira:
--     ERROR: policy "events_select_own_account" for table "events"
--            already exists
--   Esto bloquearía cualquier `supabase db push` futuro.
--
-- Fix: convertir esta migration en no-op idempotente para que el flujo
--   de migrations siga funcionando sin tocar la BD.
--
-- Detalle: SELECT 1 es completamente inofensivo y no requiere permisos
--   especiales. Si Supabase trackea esta migration como aplicada, el
--   re-apply es un no-op.
-- ═══════════════════════════════════════════════════════════════════

SELECT 1 WHERE FALSE;
