-- ═══════════════════════════════════════════════════════════════════
-- NO-OP MIGRATION — superseded by 20260514203138 + 20260514203139
-- ═══════════════════════════════════════════════════════════════════
--
-- Origen: Lovable creó esta migration como combinación de:
--   - 20260514203138_events_rls_hardening.sql
--   - 20260514203139_client_cases_closed_at.sql
--   (mismo patrón que pasó en Ola 1 con events_table)
--
-- Problema: CREATE POLICY no soporta IF NOT EXISTS en Postgres < 15.
--   Si Supabase corre las 3 migrations en orden (db reset, env nuevo),
--   la tercera tira: ERROR: policy "events_insert_authenticated_own_account"
--   already exists → bloquea supabase db push.
--
-- Fix: convertir esta migration en no-op idempotente. Las migrations
--   originales (203138 + 203139) ya cubren todo el cambio. Si Supabase
--   trackea esta migration como aplicada (timestamp 203157), el re-apply
--   es no-op.
-- ═══════════════════════════════════════════════════════════════════

SELECT 1 WHERE FALSE;
